// Questions
var q = [
  " Why did you choose to apply to this college?",
  "What are your academic goals and how do you plan to achieve them?",
  "What extracurricular activities or clubs are you interested in joining?",
  "How do you plan to contribute to the college community?",
  "Tell me about a challenge that you&#39;ve overcome.",
  "What are your personal strengths? Weaknesses?",
  "How do you plan to finance your college education?",
  "What are your long-term career goals and how do you think this college can help you achieve them?",
  "Can you describe a project or research experience you have had?",
  "Can you tell me about a time when you have been a leader or taken on a leadership role?",
  "What subject areas are you most interested in?",
  "What do you plan to study in college?",
  "What do you hope to get out of your college education?",
  "Do you know what career route you want to pursue yet?",
  "What&#39;s your favourite book, why?",
  "What have you done during the last few summers?",
  "Which activities do you hope to continue in college?",
  "Tell me about your current extracurricular involvement.",
  "What three words describe you?",
  "How would your friends descirbe you?",
  "What current event has caught your attention?",
  "Tell me about yourself",
  "What do you think is a problem that your generation faces?",
  "What do you do for fun?",
  "What are your hobbies?",
  "Tell me about influential person in your life",
  "What books do you recommend?",
  "Do you like to write?  Fiction, Non-fiction, Poetry?",
  "What kind of community service do you do?",
  "What is a memorable experience from a community service project?",
  "What song would be the soundtrack of your life right now?",
  "What have you enjoyed most about your high school?",
  "Which activites are you most passionate about, and why?",
  "How do you see yourself getting involved in the campus community?",
  "What experiences have you had with people who are different from you?",
  "What would you like the Admissions office to know that might not appear in your application?",
  "What do you most like learning about?",
  "How do you learn best?",
  "Is there anything that you would change about your high school experience?",
  "How do you spend your time when you&#39;re not in school?",
];

// Tips
var tips = [
  "Be prepared and research the college prior to the interview.",
  "Practice answering common interview questions.",
  "Dress professionally and arrive on time.",
  "Wear formals!",
  "Show enthusiasm and interest in the college and its programs.",
  "Be honest and genuine in your answers.",
  "Ask thoughtful questions to show your engagement in the college.",
  "Follow up with a thank you note after the interview.",
  "Act interested and listen to the interviewer.",
  "Speak slowly and confidently.",
  "Maintain eye-contact.",
  "Don&#39;t look here and there while thinking.",
  "Don&#39;t twitch your hands.",
  "Sit straight.",
  "If it&#39;s online, check lighting at interview time the day before",
];
